version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      #- pip install -r codebuild/requirements.txt -t lib
  
  build:
    commands:
      - echo "Zipping the Python file together!!"
      - mkdir lib
      - cd lib
      - zip -r ../my-deployment-package.zip  .
      - cd ..
      - zip -g my-deployment-package.zip lambda_function.py

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lambda-test-terraform --zip-file fileb://my-deployment-package.zip
      - echo "DONE!!"