version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r codebuild/requirements.txt -t lib
  
  build:
    commands:
      - echo "Zipping the Python file together!!"
      - cd lib
      - zip -r ../deployment_package.zip  .
      - cd ..
      - zip -g deployment_package.zip /codebuild/python/lambda_function.py

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lambda-test-terraform --zip-file fileb://deployment_package.zip
      - echo "DONE!!"